<!DOCTYPE html>
<html>
    <?php include "../templates/head.phtml" ?>
    <body>
        <!-- enregistrement -->
        <div class="container">
            <?php include "../templates/header.phtml" ?>
            <?php $current_profil = reset($profil); ?>
            <?php var_dump($current_profil); ?>
            <div class="jumbotron">
                <h1><?= $current_profil->nom_util . " " . $current_profil->prenom_util; ?></h1>
                <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
                <p><a class="btn btn-lg btn-success" href="#" role="button">Sign up today</a></p>
            </div>

            <div class="row marketing">
                <a href="logout">Déconnexion</a>

                <a href="new_mdp">Changer mot de passe</a>
                <div class="content">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="card">
                                    <div class="card-header card-chart" data-background-color="green">
                                        <div class="ct-chart" id="dailySalesChart"></div>
                                    </div>
                                    <div class="card-content">
                                        <h4 class="title">Maison</h4>
                                        <p class="category"><span class="text-success"><i class="fa fa-long-arrow-up"></i></span> Vos maisons</p>
                                        <ul class="list-group">
                                            <?php foreach ($maisons as $maison) : ?>
                                            <li class="list-group-item" data-maison-id="<?= $maison->id_maison ?>" ><button onclick="selectPiece(<?= $maison->id_maison ?>);">selectionner Maison N° <?= $maison->id_maison ?></button></li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="card">
                                    <div class="card-header card-chart" data-background-color="orange">
                                        <div class="ct-chart" id="emailsSubscriptionChart"></div>
                                    </div>
                                    <div class="card-content">
                                        <h4 class="title">Pieces</h4>
                                        <p class="category">vos pieces</p>
                                        <ul class="list-group" id="mypieces">
                                                <li class="list-group-item"  >Veuillez selectionner une maison</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="card">
                                    <div class="card-header card-chart" data-background-color="red">
                                        <div class="ct-chart" id="completedTasksChart"></div>
                                    </div>
                                    <div class="card-content">
                                        <h4 class="title">Préférences</h4>
                                        <p class="category">Vos préférences</p>
                                    </div>
                                    <div class="card-footer">
                                        <div class="stats">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="card">
                                    <div class="card-header" data-background-color="purple">
                                        <h4 class="title">Tableau de données</h4>
                                        <p class="category">Luminosité</p>
                                    </div>
                                    <div class="card-content table-responsive">
                                        <table class="table" id="table-id-l">
                                            <thead class="text-primary">
                                            <th>Nom pièce</th>
                                            <th>Date / Heure</th>
                                            <th>Valeur</th>
                                            </thead>
                                            <tbody>
                                                <?php foreach ($profil as $data) : ?>
                                                    <?php if ($data->type_capteur == 'L') : ?>
                                                        <tr>
                                                            <td><?= $data->nom_capt; ?></td>
                                                            <td><?= $data->date_value; ?></td>
                                                            <td class="text-primary"><?= $data->luminosite_lum . ' %'; ?></td>
                                                        </tr>
                                                    <?php endif; ?>
                                                <?php endforeach; ?>
                                            </tbody>
                                        </table>

                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="card">
                                    <div class="card-header" data-background-color="purple">
                                        <h4 class="title">Tableau de données</h4>
                                        <p class="category">Luminosité</p>
                                    </div>
                                    <div class="card-content table-responsive">
                                        <table class="table" id="table-id-t">
                                            <thead class="text-primary">
                                            <th>Nom pièce</th>
                                            <th>Date / Heure</th>
                                            <th>Valeur</th>
                                            </thead>
                                            <tbody>
                                                <?php foreach ($profil as $data) : ?>
                                                    <?php if ($data->type_capteur == 'T') : ?>
                                                        <tr>
                                                            <td><?= $data->nom_capt; ?></td>
                                                            <td><?= $data->date_value; ?></td>
                                                            <td class="text-primary"><?= $data->temperature_temp . ' °C'; ?></td>
                                                        </tr>
                                                    <?php endif; ?>
                                                <?php endforeach; ?>
                                            </tbody>
                                        </table>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php include "../templates/footer.phtml" ?>
        </div>
        <?php include "../templates/script.phtml" ?>
    </body>
</html>
