<!DOCTYPE html>
<html>
    <?php include "../templates/head.phtml" ?>
    <body>
        <!-- enregistrement -->
        <div class="container">
            <?php include "../templates/header.phtml" ?>
            <?php $current_profil = reset($profil); ?>
            <?php var_dump($current_profil); ?>
            <div class="jumbotron">
                <h1><?= $current_profil->nom_util . " " . $current_profil->prenom_util; ?></h1>
                <ul class="list-group" id="user_info">
                    <li class="list-group-u"  ><?= $current_profil->adresse_util;?></li>
                    <li class="list-group-u"  ><?= $current_profil->ville_util;?></li>
                    <li class="list-group-u"  ><?= $current_profil->cp_util;?></li>
                    <li class="list-group-u"  ><?= $current_profil->tel_util;?></li>    
                </ul>
                <p><a class="btn btn-lg btn-success" href="#" role="button">Modifier</a></p>
            </div>

            <div class="row marketing">
                <a href="logout">Déconnexion</a>

                <a href="new_mdp">Changer mot de passe</a>
                <div class="content">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="card">
                                    <div class="card-header card-chart" data-background-color="green">
                                        <div class="ct-chart" id="dailySalesChart">
                                            <div class="text-center">
                                                <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="card-content">
                                        <h4 class="title">Maison</h4>
                                        <p class="category"><span class="text-success"><i class="fa fa-long-arrow-up"></i></span> Vos maisons</p>
                                        <ul class="list-group">
                                            <?php foreach ($maisons as $maison) : ?>
                                                <li class="list-group-item" data-maison-id="<?= $maison->id_maison ?>" ><button onclick="selectMaison(<?= $maison->id_maison ?>);">selectionner Maison N° <?= $maison->id_maison ?></button></li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-3">
                                <div class="card">
                                    <div class="card-header card-chart" data-background-color="orange">
                                        <div class="ct-chart" id="emailsSubscriptionChart"></div>
                                    </div>
                                    <div class="card-content">
                                        <h4 class="title">Pieces</h4>
                                        <p class="category">vos pieces</p>
                                        <ul class="list-group" id="mypieces">
                                            <li class="list-group-item"  >Veuillez selectionner une piece</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="card">
                                    <div class="card-header card-chart" data-background-color="orange">
                                        <div class="ct-chart" id="emailsSubscriptionChart"></div>
                                    </div>
                                    <div class="card-content">
                                        <h4 class="title">Capteurs</h4>
                                        <p class="category">vos capteurs</p>
                                        <ul class="list-group" id="mycaptors">
                                            <li class="list-group-item"  >Veuillez selectionner un capteur</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="card">
                                    <div class="card-header card-chart" data-background-color="red">
                                        <div class="ct-chart" id="completedTasksChart"></div>
                                    </div>
                                    <div class="card-content">
                                        <h4 class="title">Préférences</h4>
                                        <p class="category">Vos préférences</p>
                                    </div>
                                    <div class="card-footer">
                                        <div class="stats">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row" id='table-values'>
                            <div class="col-md-12">
                                <div class="card">
                                    <div class="card-header" data-background-color="purple">
                                        <h4 class="title">Tableau de données</h4>
                                        <p class="category">Luminosité</p>
                                    </div>
                                    <div class="card-content table-responsive">
                                        <table class="table" id="mycaptortype">

                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php include "../templates/footer.phtml" ?>
        </div>
        <?php include "../templates/script.phtml" ?>
    </body>
</html>
