<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>
        <h1>Ecolight</h1>
        <div class="btn-group" role="group" aria-label="...">
            <a href="index.php/login"><button type="button" class="btn btn-default">se connecter</button></a>
            <a href="index.php/register"><button type="button" class="btn btn-default">s'enregistrer</button></a>
        </div>
    </body>
</html>


