<!DOCTYPE html>
<html>
    <?php include "../templates/head.phtml" ?>
    <body>

        <div class="wrapper">



            <div class="main-panel">
                <div class="content">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <div class="btn-group btn-group-lg" role="group" aria-label="...">
                                    <a href="index.php/login"><button type="button" class="btn btn-default">Se connecter</button></a>
                                    <a href="index.php/register"><button type="button" class="btn btn-default">S'enregistrer</button></a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <?php include "../templates/footer.phtml" ?>
        </div>
        <?php include "../templates/script.phtml" ?>
    </body>
</html>


