<!DOCTYPE html>
<html>
    <?php include "../templates/head.phtml" ?>
    <body>

    <div class="container">
            <p> <?php if (!empty($message)) { echo $message;} ?> </p>
            <p> <?php if (!empty($hello)) { echo $hello;} ?> </p>
      <form class="form-signin" action="doLogin" method="POST">
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="email" class="sr-only">Email address</label>
        <input type="email" id="email" class="form-control" placeholder="Email address" required autofocus>
        <label for="password" class="sr-only">Password</label>
        <input type="password" id="password" class="form-control" placeholder="Password" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Se coçnnecter</button>
      </form>
                               <div class="btn-group btn-group-lg" role="group" aria-label="...">
                                    <a href="new_mdp"><button type="button" class="btn btn-default">Mot de passe oublié ?</button></a>
                                    <a href="register"><button type="button" class="btn btn-default">S'enregistrer</button></a>
                                </div>

            <?php include "../templates/footer.phtml" ?>
        </div>
        <?php include "../templates/script.phtml" ?>
    </body>
</html>
