<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <div class="text-center" style="padding:50px 0">
            <div class="logo">Mot de passe oublié</div>
            <!-- Main Form -->
            <div class="login-form-1">
                <form id="forgot-password-form" class="text-left">
                    <div class="etc-login-form">
                        <p>Modifiez votre mot de passe</p>
                    </div>
                    <div class="login-form-main-message"></div>
                    <div class="main-login-form">
                        <div class="login-group">
                            <div class="form-group">
                                <label for="password" class="sr-only">Mot de passe :</label>
                                <input type="password" class="form-control" id="password" name="password" placeholder="mot de passe" required>
                            </div>
                            <div class="form-group">
                                <label for="new_password" class="sr-only">Nouveau mot de passe :</label>
                                <input type="new_password" class="form-control" id="password" name="new_password" placeholder="nouveau mot de passe" required>
                            </div>
                        </div>
                        <button type="submit" class="login-button"><i class="fa fa-chevron-right"></i></button>
                    </div>
                    <div class="etc-login-form">
                        <p>Déja un compte ? <a href="login">Connexion</a></p>
                        <p>Nouvel utilisateur ? <a href="register">Créer un nouveau compte</a></p>
                    </div>
                </form>
            </div>
            <!-- end:Main Form -->
        </div>

    </body>
</html>


