<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <!-- enregistrement -->

        <div class="text-center" style="padding:50px 0">
            <div class="logo">Enregistrement</div>
            <?= ( $save) ? '' : 'Mot de passe incorect, veuillez recommencer'; ?>
            <p></p>
            <div class="login-form-1">
                <form id="register-form" class="text-left" action="index.php/doRegister" method="POST">
                    <div class="login-form-main-message"></div>
                    <div class="main-login-form">
                        <div class="login-group">

                            <div class="form-group">
                                <label for="login" class="sr-only"> Login :</label>
                                <input type="text" class="form-control" id="login" name="login" placeholder="login" required>
                            </div>
                            <div class="form-group">
                                <label for="password" class="sr-only">Mot de passe :</label>
                                <input type="password" class="form-control" id="password" name="password" placeholder="mot de passe" required>
                            </div>
                            <div class="form-group">
                                <label for="password_confirm" class="sr-only">Confirmer :</label>
                                <input type="password" class="form-control" id="password_confirm" name="password_confirm" placeholder="mot de passe" required>
                            </div>
                            <div class="form-group">
                                <label for="email" class="sr-only">Email :</label>
                                <input type="email" class="form-control" id="email" name="email" placeholder="email" required>
                            </div>
                            <div class="form-group">
                                <label for="nom" class="sr-only">Nom  :</br></label>
                                <input type="text" class="form-control" id="nom" name="nom" placeholder="nom">
                            </div>
                            <div class="form-group">
                                <label for="prenom" class="sr-only">Prenom  :</label>
                                <input type="text" class="form-control" id="prenom" name="prenom" placeholder="prénom">
                            </div>
                            <div class="form-group">
                                <label for="adresse" class="sr-only"> Adresse :</label>
                                <input type="text" class="form-control" id="adresse" name="adresse" placeholder="votre adresse" required>
                            </div>
                            <div class="form-group">
                                <label for="ville" class="sr-only">Ville :</br></label>
                                <input type="text" class="form-control" id="ville" name="ville" placeholder="ville" required>
                            </div>
                            <div class="form-group">
                                <label for="cp" class="sr-only">Code postal :</label>
                                <input type="text" class="form-control" id="cp" name="cp" placeholder="code postal" required>
                            </div>
                            <div class="form-group">
                                <label for="tel" class="sr-only">Téléphone :</label>
                                <input type="text" class="form-control" id="tel" name="tel" placeholder="téléphone" required>
                            </div>
                            <!--	<div class="form-group login-group-checkbox">
                                        <input type="radio" class="" name="reg_gender" id="male" placeholder="username">
                                        <label for="male">male</label>

                                        <input type="radio" class="" name="reg_gender" id="female" placeholder="username">
                                        <label for="female">female</label>
                                    </div>-->
                            <!--	<div class="form-group login-group-checkbox">
                                        <input type="checkbox" class="" id="reg_agree" name="reg_agree">
                                        <label for="reg_agree">i agree with <a href="#">terms</a></label>
                                    </div>-->

                        </div>
                        <input type="submit" name="enregistrer" value="Enregistrer" class="button">
                    </div>
                    <div class="etc-login-form">
                        <p>Déja un compte? <a href="login">Se connecter</a></p>
                    </div>
                </form>
            </div>
        </div>
    </body>
</html>

