<?php
if ($assets_home) {
    $assets_path = null;
} else {
    $assets_path = '../';
}
?>
<!--   Core JS Files   -->
<script src="<?= $assets_path; ?>assets/js/jquery-3.1.0.min.js" type="text/javascript"></script>
<script src="<?= $assets_path; ?>assets/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?= $assets_path; ?>assets/js/material.min.js" type="text/javascript"></script>

<!--  Charts Plugin -->
<script src="<?= $assets_path; ?>assets/js/chartist.min.js"></script>

<!--  Notifications Plugin    -->
<script src="<?= $assets_path; ?>assets/js/bootstrap-notify.js"></script>

<!-- Material Dashboard javascript methods -->
<script src="<?= $assets_path; ?>assets/js/material-dashboard.js"></script>

<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js" type="text/javascript"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $('#table-values').hide();
    });
    function selectMaison(id) {
        $('#table-values').hide();
        $.ajax({
            url: 'getPieceByIdMaison',
            type: 'POST',
            dataType: 'text',
            data: {
                id: JSON.stringify(id)
            },
            success: function (data) {
                var emptydiv = $('#mypieces');
                var emptydivli = emptydiv.find('li');
                emptydivli.remove();
                emptydiv.append(JSON.parse(data));
            }
        });

    }

    function selectPiece(id) {
        $('#table-values').hide();
        $.ajax({
            url: 'getCaptorByIdPiece',
            type: 'POST',
            dataType: 'text',
            data: {
                id: JSON.stringify(id)
            },
            success: function (data) {
                var emptydiv = $('#mycaptors');
                var emptydivli = emptydiv.find('li');
                emptydivli.remove();
                emptydiv.append(JSON.parse(data));
            }
        });

    }

    function selectCaptor(id, type) {

        $.ajax({
            url: 'getValuesByCaptorId',
            type: 'POST',
            dataType: 'text',
            data: {
                id: JSON.stringify(id),
                type: type
            },
            success: function (data) {
                var emptydiv = $('#mycaptortype');
                var emptydivthead = emptydiv.find('thead');
                var emptydivtbody = emptydiv.find('tbody');
                emptydivthead.remove();
                emptydivtbody.remove();
                emptydiv.append(JSON.parse(data));
                /*$('#mycaptortype').DataTable({
                    "language": {
                        "lengthMenu": "Display _MENU_ records per page",
                        "zeroRecords": "Nothing found - sorry",
                        "info": "Showing page _PAGE_ of _PAGES_",
                        "infoEmpty": "No records available",
                        "infoFiltered": "(filtered from _MAX_ total records)"
                    }
                });*/
                $('#table-values').show();

            }
        });

    }
</script>

